#!/bin/bash

##installing packages

echo $USR_PWD | sudo -S "pacman -S xorg xorg-server xorg-xinit xorg-xrandr xorg-font-utils xorg-xinput xorg-xev xorg-xbacklight i3  --noconfirm"
echo $USR_PWD | sudo -S "pacman -S feh ffmpeg thunar tar screenfetch scrot lxappearance imagemagick ntfs-3g unzip rofi compton conky --noconfirm" 
echo $USR_PWD | sudo -S "pacman -S base-devel htop autoconf automake binutils fakeroot --noconfirm"
echo $USR_PWD | sudo -S "pacman -S libreoffice noto-fonts powerline-fonts mplayer qutebrowser chromium firefox breeze-icons mesa --noconfirm"
echo $USR_PWD | sudo -S "pacman -S sakura tmux git fish ranger --noconfirm"
echo $USR_PWD | sudo -S "pacman -S gvfs gvfs-mtp libmtp thunar-archive-plugin thunar-media-tags-plugin thunar-volman ffmpegthumbnailer tumbler --noconfirm"
echo $USR_PWD | sudo -S "pacman -S meld --noconfirm" 
echo $USR_PWD | sudo -S "pacman -S pulseaudio-alsa pulseaudio-bluetooth bluez bluez-libs bluez-utils bluez-firmware  --noconfirm"pulseaudio-bluetooth alsa-plugins --noconfirm"
echo $USR_PWD | sudo -S "pacman -S mcomix zathura-pdf-mupdf --noconfirm"
echo $USR_PWD | sudo -S "pacman -S sqlite sqlitebrowser putty freecad blender --noconfirm"

#Setting yaourt
echo $USR_PWD | sudo -S "pacman -S --needed base-devel git wget yajl  --noconfirm"
